create table "public"."notes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_book_id" bigint,
    "text" text not null,
    "page_number" integer
);


alter table "public"."notes" enable row level security;

create table "public"."reading_goals" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_book_id" bigint,
    "user_id" uuid not null,
    "goal_type" text,
    "start_date" date,
    "end_date" date,
    "deadline" date,
    "status" text
);


alter table "public"."reading_goals" enable row level security;

create table "public"."reading_sessions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_book_id" bigint not null,
    "pages_read" smallint,
    "time_spent" integer,
    "start_page" integer,
    "end_page" integer,
    "notes" text
);


alter table "public"."reading_sessions" enable row level security;

CREATE UNIQUE INDEX notes_pkey ON public.notes USING btree (id);

CREATE UNIQUE INDEX reading_goals_pkey ON public.reading_goals USING btree (id);

CREATE UNIQUE INDEX reading_sessions_pkey ON public.reading_sessions USING btree (id);

alter table "public"."notes" add constraint "notes_pkey" PRIMARY KEY using index "notes_pkey";

alter table "public"."reading_goals" add constraint "reading_goals_pkey" PRIMARY KEY using index "reading_goals_pkey";

alter table "public"."reading_sessions" add constraint "reading_sessions_pkey" PRIMARY KEY using index "reading_sessions_pkey";

alter table "public"."notes" add constraint "notes_user_book_id_fkey" FOREIGN KEY (user_book_id) REFERENCES user_books(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notes" validate constraint "notes_user_book_id_fkey";

alter table "public"."reading_goals" add constraint "reading_goals_user_book_id_fkey" FOREIGN KEY (user_book_id) REFERENCES user_books(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."reading_goals" validate constraint "reading_goals_user_book_id_fkey";

alter table "public"."reading_goals" add constraint "reading_goals_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."reading_goals" validate constraint "reading_goals_user_id_fkey";

alter table "public"."reading_sessions" add constraint "reading_sessions_user_book_id_fkey" FOREIGN KEY (user_book_id) REFERENCES user_books(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."reading_sessions" validate constraint "reading_sessions_user_book_id_fkey";

grant delete on table "public"."notes" to "anon";

grant insert on table "public"."notes" to "anon";

grant references on table "public"."notes" to "anon";

grant select on table "public"."notes" to "anon";

grant trigger on table "public"."notes" to "anon";

grant truncate on table "public"."notes" to "anon";

grant update on table "public"."notes" to "anon";

grant delete on table "public"."notes" to "authenticated";

grant insert on table "public"."notes" to "authenticated";

grant references on table "public"."notes" to "authenticated";

grant select on table "public"."notes" to "authenticated";

grant trigger on table "public"."notes" to "authenticated";

grant truncate on table "public"."notes" to "authenticated";

grant update on table "public"."notes" to "authenticated";

grant delete on table "public"."notes" to "service_role";

grant insert on table "public"."notes" to "service_role";

grant references on table "public"."notes" to "service_role";

grant select on table "public"."notes" to "service_role";

grant trigger on table "public"."notes" to "service_role";

grant truncate on table "public"."notes" to "service_role";

grant update on table "public"."notes" to "service_role";

grant delete on table "public"."reading_goals" to "anon";

grant insert on table "public"."reading_goals" to "anon";

grant references on table "public"."reading_goals" to "anon";

grant select on table "public"."reading_goals" to "anon";

grant trigger on table "public"."reading_goals" to "anon";

grant truncate on table "public"."reading_goals" to "anon";

grant update on table "public"."reading_goals" to "anon";

grant delete on table "public"."reading_goals" to "authenticated";

grant insert on table "public"."reading_goals" to "authenticated";

grant references on table "public"."reading_goals" to "authenticated";

grant select on table "public"."reading_goals" to "authenticated";

grant trigger on table "public"."reading_goals" to "authenticated";

grant truncate on table "public"."reading_goals" to "authenticated";

grant update on table "public"."reading_goals" to "authenticated";

grant delete on table "public"."reading_goals" to "service_role";

grant insert on table "public"."reading_goals" to "service_role";

grant references on table "public"."reading_goals" to "service_role";

grant select on table "public"."reading_goals" to "service_role";

grant trigger on table "public"."reading_goals" to "service_role";

grant truncate on table "public"."reading_goals" to "service_role";

grant update on table "public"."reading_goals" to "service_role";

grant delete on table "public"."reading_sessions" to "anon";

grant insert on table "public"."reading_sessions" to "anon";

grant references on table "public"."reading_sessions" to "anon";

grant select on table "public"."reading_sessions" to "anon";

grant trigger on table "public"."reading_sessions" to "anon";

grant truncate on table "public"."reading_sessions" to "anon";

grant update on table "public"."reading_sessions" to "anon";

grant delete on table "public"."reading_sessions" to "authenticated";

grant insert on table "public"."reading_sessions" to "authenticated";

grant references on table "public"."reading_sessions" to "authenticated";

grant select on table "public"."reading_sessions" to "authenticated";

grant trigger on table "public"."reading_sessions" to "authenticated";

grant truncate on table "public"."reading_sessions" to "authenticated";

grant update on table "public"."reading_sessions" to "authenticated";

grant delete on table "public"."reading_sessions" to "service_role";

grant insert on table "public"."reading_sessions" to "service_role";

grant references on table "public"."reading_sessions" to "service_role";

grant select on table "public"."reading_sessions" to "service_role";

grant trigger on table "public"."reading_sessions" to "service_role";

grant truncate on table "public"."reading_sessions" to "service_role";

grant update on table "public"."reading_sessions" to "service_role";


